name: Deploy to Kaggle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          cat > ~/.kaggle/kaggle.json << EOF
          {
            "username": "${{ secrets.KAGGLE_USERNAME }}",
            "key": "${{ secrets.KAGGLE_API_KEY }}"
          }
          EOF
          chmod 600 ~/.kaggle/kaggle.json

      - name: Install Kaggle CLI
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Confirm Kaggle User
        run: kaggle config view
      
      - name: Debug folder
        run: |
          ls -R

      - name: Push Notebook
        run: kaggle kernels push -p notebooks

