name: Deploy to Kaggle

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Latest Kaggle
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade kaggle

      - name: Show Kaggle Version
        run: kaggle --version

      - name: Test Kaggle Auth
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          kaggle competitions list

      - name: Push notebook
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          kaggle kernels push -p notebooks/