name: Deploy to Kaggle

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Push notebook to Kaggle
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          echo $KAGGLE_API_TOKEN  # for debug (*** masked)
          kaggle kernels push -p notebooks/